CXX=g++
LD=g++

BRIDGES_INC=$(HOME)/prgs/bridges-cxx/src
RAPIDJSON_INC=$(HOME)/prgs/rapidjson/include/

CXXFLAGS= -std=c++14 -I $(BRIDGES_INC) -I $(BRIDGES_INC)/data_src -I $(RAPIDJSON_INC)

LDLIBS=-lcurl

ListIMDB:

